### ISSUE TITLE
Is there a way to host this on a local system?

### ISSUE THREAD

**Issue by shutterbug2000** [yellows8/3ds_browserhax_common#1]
Whenever I try to put this on a local webserver, it never seems to even run, I just crash back to the home menu. Any ideas?

Thanks!

**Comment by yellows8** [comment]
How exactly did you set it up?

**Comment by shutterbug2000** [comment]
I have 3dsbrowserhax_common.php, 3dsbrowserhax_webkit_r158724.php, and browserhax_cfg_example.php in the same folder, with 3dsbrowserhax_webkit_r158724.php including browserhax_cfg_example.php. In the config,    $ropchainselect = 0, which should trigger the black error screen(I believe), but instead just throws me to the home menu.

**Comment by yellows8** [comment]
The HTTP arm11code loading with gspwn is the only mode that's guaranteed to work with sliderhax, since that's the only one I really test with. Everything else, no idea if the heap addrs are even correct.

**Comment by shutterbug2000** [comment]
Well, if I go to http://yls8.mtheall.com/sliderhax.php?rop=0, it triggers the black screen error, also, even if I do ropchainselect = 2, and arm11code_loadfromsd=0, 1, or 2, still kicks me to home menu, leading me to believe there's something wrong with my setup.

**Comment by yellows8** [comment]
Well with the HTTP loading one you need the binary setup on the server(don't count on SD loading working for the same reason mentioned above).

**Comment by shutterbug2000** [comment]
Ok, I can't seem to make this work at all. I have the binary on the server, I try to connect, and every single time, it fails. ROP chain is 2, load from sd is 2. What could I be doing wrong?

**Comment by yellows8** [comment]
Trying clearing browser savedata like the README already mentioned.

**Comment by shutterbug2000** [comment]
I already have, multiple times.

**Comment by yellows8** [comment]
FWIW I had weird issues a long time ago where it was far more unstable depending on the URL, don't know if that's relevant for you or not.

**Comment by shutterbug2000** [comment]
Could be, do you test locally? If so, what local ip do you use so I could set the server to that to see.

**Comment by yellows8** [comment]
http://{serverip}/{scriptname_also_used_in_the_haxrepo}

**Comment by yellows8** [comment]
Weird, it worked fairly well under my SD-nandimage for v10.1 with a local URL(last time I tried), but on unmodded-FIRM v10.1 it's awful(never worked once when I was trying). But of course an URL on the yls8\* server with just one character change in the URL works fine....

**Comment by shutterbug2000** [comment]
Yeah, same thing I'm running into here.

**Comment by yellows8** [comment]
Anyway, this is specific to sliderhax(3ds_webkithax repo) aka not this 3ds_browserhax_common repo, so closing this.
