### ISSUE TITLE
installing homebrew will give updating unstable :(

### ISSUE THREAD

**Issue by XxnoobslayerxX** [yellows8/3ds_browserhax_common#10]
well i've got browserhax but i try updating to the latest firmware but it will begin to say the f%&king same error so does ANYONE know how to fix? no, i did not install RXtools PLZ HELP!

**Comment by yellows8** [comment]
There's no reason for homebrew to break doing sysupdates. Perhaps your DNS settings aren't the default?

**Comment by XxnoobslayerxX** [comment]
youre right it worked  after changing

**Comment by XxnoobslayerxX** [comment]
will menuhax still work when 10.6 releases BUT i've never downloaded latest??? (plz say yes)

**Comment by XxnoobslayerxX** [comment]
will menuhax still work when 10.6 releases BUT i've never downloaded latest??? (plz say yes)

**Comment by XxnoobslayerxX** [comment]
will menuhax still work when 10.6 releases BUT i've never downloaded latest??? (plz say yes)

**Comment by XxnoobslayerxX** [comment]
will menuhax still work when 10.6 releases BUT i've never downloaded latest??? (plz say yes)

**Comment by yellows8** [comment]
No reason why not if you'd still be on v10.5.

**Comment by fox8091** [comment]
Can this issue be closed now?
