### ISSUE TITLE
browserhax 2ds on 9.8.0 sliderhax not working

### ISSUE THREAD

**Issue by efrtt** [yellows8/3ds_browserhax_common#12]
i was reading another person's issue on this, and i'm getting the exact same issue (flashes yellow but crashes). i followed every guide i could find. however, both of us updated our systems using a game card. as a suggestion, you said to do a full update, how would one do that without updating to 10.5 ?

**Comment by yellows8** [comment]
Sounds like HTTP-download is failing. https://github.com/yellows8/3ds_browserhax_common#homebrew-launcher

**Comment by efrtt** [comment]
anything i could do for now or?

**Comment by efrtt** [comment]
does it matter if i updated my 3ds through a game card?
