### ISSUE TITLE
Enable the hack to be accessed through http://107.211.140.65/3dsbrowserhax_auto.php

### ISSUE THREAD

**Issue by Guedez** [yellows8/3ds_browserhax_common#14]
Even with the nag blocking me, if I put some invalid dns, and try to access directly through the IP, I get the Not Found message.

It was the only internet page that my browser have ever shown after the nag started.

Maybe this can bypass the nag, if, instead of showing the 'not found', it shows the actual page as if being accessed by the url

**Comment by yellows8** [comment]
Not sure what "nag" you're talking about.

**Comment by Guedez** [comment]
The 'nag' is the 'You need to update your system before using the browser' popup that appears when I try to use the hack through normal means

**Comment by yellows8** [comment]
Old3DS or New3DS?

**Comment by Guedez** [comment]
new3DS, european, version 9.9

**Comment by yellows8** [comment]
There's already tutorial(s) for bypassing that block on New3DS(see gbafail).

**Comment by Guedez** [comment]
I have tried variations of that before, but I will still try that specific procedure anyways.

Either way, I risk being conceited since I know almost nothing about how the browser works or even the browserhax itself, But I believe that enabling direct IP access might create a granted way to access browserhax for those with the blocking popup

**Comment by fox8091** [comment]
The "blocking popup" you're referring to is something that is in the web-browser savedata. Local IP or web address, that trick is the _only_ way to bypass it.

**Comment by yellows8** [comment]
Also the bypass on the browserhax_site.
