### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by LightHax** [yellows8/3ds_browserhax_common#15]
Each time I use the URL (yls8.mtheall.com/3dsbrowserhax_auto.php) the yellow screen appear, the grey, and the orange. But at orange screen, the chargement is not loading and my page crash, and I return with an error at the 3ds menu. Please help!  My old 3ds is 10.5 and I use Homebrew launcher 10.4.

**Comment by ShayBox** [comment]
same issue, i have an OLD 3DS 10.5.0-30U and browser V1.7616 and i use http://mtheall.com/3dsbrowserhax_auto.php i've tried all the links though, auto worked a few times but stopped working after a crash, and nomatter howmany times i format or clean my sdcard it doesnt work anymore.

**Comment by razorclaw** [comment]
I have the same exact problem. I feel like it has something to do with the DNS server

**Comment by ShayBox** [comment]
It might be, i have a network-wide adblocker as my routers DNS

**Comment by razorclaw** [comment]
I remember when tubehax was possible, you had to change your DNS server. Maybe that's still a thing with the web browser, and we're just separate people that didn't notice that on the instructions for homebrew
