### ISSUE TITLE
Crashing after yellow screen

### ISSUE THREAD

**Issue by regortaz** [yellows8/3ds_browserhax_common#16]
I've got a pretty old 3DS with with **v5.1.0-11E** having browser version **1.7552**. 
I've downloaded and put the files into the original SD card that came with the unit and attempted to launch via sliderhax but no luck so far. I've tried like an hour each time clicking on a different part of the slider and messing with A button and stuff but no luck. Every single time it **crashes to home screen** **after the yellow screen** hanging for like 3 seconds **saying** "**An error has occured. Please save your data in any software currently in use, then restart the system**.". 
The issue is very similar to [this](https://github.com/yellows8/3ds_browserhax_common/issues/6).
Is there anything else that I can try or my unit/firmware is not supported somehow?

Thanks in advance.

EDIT: And yes I've tried with different networks. Used my WiFi with my ISP DNS, with Google DNS and my phone's 3G connection.

**Comment by yellows8** [comment]
Please read the browserhax_site properly.
