### ISSUE TITLE
1 out of every 30 tries or more

### ISSUE THREAD

**Issue by LokeYourC3PH** [yellows8/3ds_browserhax_common#17]
So, is there any way to fix that with the annoying Browser crash? Its really an annoyance, because i can get BrowserHax started like every 30th time or even more if i am unlucky, and it just isn't fun anymore after a while. I also see many people having custom files on their SDCard, while i always reset mine with fresh files, but it still fails 95% of the time, until it just ends up magically working. Sometimes i change the time to 1.1.2000 and 00:00, then i change the router its connected to, i always clear the browser for everything (resetting it), trying to reapply the Standard Theme (even if it is applied) and such, and yet there is a small chance of it working at all. Any fix for this at all?

**Comment by LokeYourC3PH** [comment]
Most of the time it just gets stuck on the 2nd yellow screen, then crashing to the main menu.

**Comment by LokeYourC3PH** [comment]
The reason for this is also that, if i want to apply a Theme through the main 3DS launcher, it is VERY hard getting back into Homebrew without having reset the theme to Standard at least once. That makes the custom themeing even harder, as using the Standard theme does not work very well, because the theme isn't being saved upon reboot, which is very sad. Its somewhat of a paradox, either Homebrew but no themeing, or themeing and no Homebrew.

**Comment by yellows8** [comment]
Why aren't you using menuhax?

**Comment by LokeYourC3PH** [comment]
Well i did, but when i wanted to apply another theme, it went off again, so i need to get back in to reapply menuhax, but its first about getting back in :/

**Comment by Salurius** [comment]
then don't change theme

**Comment by LokeYourC3PH** [comment]
Thanks for that useless insight, i'm going to remember that the next i wanna use Homebrew for exactly that.
