### ISSUE TITLE
Fails to load payload after first succesful time

### ISSUE THREAD

**Issue by DoumanAsh** [yellows8/3ds_browserhax_common#18]
New 3DS 10.3
Using reset with date change.

First time i was able to run payload but it turns out i forgot to set-up home menu themes and so menuhax didn't let me install anything.

I have installed home menu extradata but now payload never loads from browserhax.
It just gets me bad certificate and error that video cannot be loaded.

Should i just try and try or could it be something went wrong?

**Comment by yellows8** [comment]
HTTP->HTTPS redirect broke browserhax/etc, this will be fixed server-side.

**Comment by yellows8** [comment]
It works fine now with plain-http.

**Comment by DoumanAsh** [comment]
Thanks
