### ISSUE TITLE
3DS 10.6 HOMEBREW LAUNCHER PROBLEM 

### ISSUE THREAD

**Issue by LightHax** [yellows8/3ds_browserhax_common#19]
Hi. I just up my 3ds to 10.6. But homebrew launcher is not loading, i have no color screens, Just a text. I want install rxTools,  but i don't know how to install this. Pls how to use the homebrew launcher ?

**Comment by yellows8** [comment]
You can't read the site hosting said hax ........

**Comment by LightHax** [comment]
It's writed : 
This browser version is not recognized/supported by 3ds_browserhax_common.

**Comment by Salurius** [comment]
I have the same problem but i think i know where the error lies i have Browser Version 1.7622 and latest version here is 1.7616

**Comment by Salurius** [comment]
how long do you think you need to include this version?

**Comment by LightHax** [comment]
Huh, sorry, i'm french but i speak english, can you write this in french pls ?

**Comment by Salurius** [comment]
J'ai le même problème, mais je pense que je sais où se trouve l'erreur i have Browser Version 1,7622 et dernière version ici est 1,7616

**Comment by yellows8** [comment]
Please actually _read_ the browserhax_site (or even 3dbrew).
