### ISSUE TITLE
3DS stuck on startup

### ISSUE THREAD

**Issue by zer0key123** [yellows8/3ds_browserhax_common#2]
When I try to start browserhax, it gets stuck on the starting screen. Picture:
![image](https://cloud.githubusercontent.com/assets/6163889/10561368/88606bf0-751d-11e5-8c19-fc558a2e26a8.png)

**Comment by smealum** [comment]
make sure you have boot.3dsx at the root of your SD card.

**Comment by zer0key123** [comment]
Oh. Apparently i forgot to do that
