### ISSUE TITLE
10.2.0-28U Yellow screens and crashes

### ISSUE THREAD

**Issue by FlamingIce151** [yellows8/3ds_browserhax_common#22]
I have a Old3DS with 10.2.0.28U. I have my Date and time set to Jan 1st 00:00 and have initialized savedata. I scanned the QR code the Bottom screen turns yellow but the top screen still moves. after a few second it brings up an error message saying 
"An error has occurred. Hold down the POWER Button to turn off the power, then turn it on and try again" and the nintendo site. My SD card has all the files needed. I just dont know what to do.

**Comment by yellows8** [comment]
How many times did you try where it did that? "Bottom screen turns yellow but the top screen still moves. "

**Comment by FlamingIce151** [comment]
Ive tried it at least 15 times. Here is exactly what is happening : https://www.youtube.com/watch?v=E1-wOIuWigo

**Comment by yellows8** [comment]
Are you certain your SD card is really inserted in that 3DS?

**Comment by FlamingIce151** [comment]
Yes i am. and it has all the files needed

**Comment by FlamingIce151** [comment]
Oh my god it wasnt fully connected. Damnit. Soooooo sorry for wasting your time.
