### ISSUE TITLE
you said your not going to work on free for a while

### ISSUE THREAD

**Issue by ashhax14** [yellows8/3ds_browserhax_common#24]
can we get an idea on when it is going to be worked on?obviously not the exact date.
plsss tell us(browserhax/menu)

**Comment by yellows8** [comment]
Browserhax might get done faster if people would help with the browser vuln-testing/etc, instead of 100% begging.

I want to finish other things before starting on that.

**Comment by ghost** [comment]
i can test it for you,i have emunand+hardmod and a9lh
so i could do vuln testing for you

**Comment by yellows8** [comment]
@AlexS2412 #27
