### ISSUE TITLE
Browserhax is Probably Dead.

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_browserhax_common#26]
I'm using an older system firmware, and due to Nintendo's updated servers, all online features are blocked on older firmware versions, this includes the internet browser.  Unlike other online applications, ctr-httpwn does not allow access to the internet browser.  Since browserhax is only available to older firmware versions and there is no way to access the internet browser on these versions, browserhax is dead until a 10.7 alternative is found.  This is my speculation.

**Comment by yellows8** [comment]
"Since browserhax is only available to older firmware versions and there is no way to access the internet browser on these versions" Please actually _read_ the browserhax_site.
