### ISSUE TITLE
An ask for you

### ISSUE THREAD

**Issue by DD2XAlpha** [yellows8/3ds_browserhax_common#27]
Hi there!, Im just going to ask how can I run unsigend code on 3DS, Im a student  on HTML (Im developing a web Beta... but I think I will never release that page) and another programming lenguajes... So, I mean I want to develop a Hax or a Homebrew app... Only I want to know what kind of lenguaje I need to know?... and the last question is... after I updet to 10.7.0-32 I recibed another Update!! But I never see info on internet... I still on 10.7.0-32... 
# HopeBrowserHaxWorksAgainOn3DS #HopesAndDreamsOnAFreeHaxFor10.7

**Comment by yellows8** [comment]
"after I updet to 10.7.0-32 I recibed another Update!! But I never see info on internet... I still on 10.7.0-32... " Nonsense. https://yls8.mtheall.com/ninupdates/reports.php

If anyone really want to help, then try using crash-trigger WebKit test-cases(from the WebKit SVN) with the latest web-browser to see if any crash occurs. Do not send any such test-cases publicly, it should be done privately via IRC.

**Comment by DD2XAlpha** [comment]
thx
