### ISSUE TITLE
2.1.0-4E not working ;_;

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_browserhax_common#3]
I ran this on my 3DS: http://yls8.mtheall.com/3dsbrowserhax_auto.php but it doesn't work.

I put boot.3dsx on the root of my SD card and I've even cleared the cache. The console is completely new and is running 2.1.0-4E.

When launching the payload, it works until I try moving the slider, in which case it freezes. I also made a post of it, on that forum: http://gbatemp.net/threads/backing-up-nand-on-2-1-0-4e.400302/

Do you have any info that I could go by? Thank you!

**Comment by yellows8** [comment]
Notice the lowest supported systme-version...... https://smealum.github.io/3ds

**Comment by ghost** [comment]
I was looking at this part of the readme:

1.7455 v1024/2.1.0-4..3.0.0-6

So I thought it would at least do something :( No NAND backup for meh. Thanks anyways :D
