### ISSUE TITLE
New3DS 10.5.0-26K stuck at gray screen.

### ISSUE THREAD

**Issue by Patron182** [yellows8/3ds_browserhax_common#31]
Hi, i have a new 3ds from korea when i try to install the browserhax the bottom screen goes yellow then gray and then nothing happens, i hope the support to 10.5.0-26K come soon.

Bye.

**Comment by yellows8** [comment]
It's not fully supported yet. https://github.com/smealum/ninjhax2.x/pull/7

**Comment by d3m3vilurr** [comment]
temporary solution
1. download http://bhx.suod.kr/payloads/ropbin/N3DS_10.5K_ROP.bin
2. rename filename to `browserhax_hblauncher_ropbin_payload.bin`
3. copy to sdcard root
4. relaunch browserhax

**Comment by Patron182** [comment]
It works perfectly. Thank you :)

Once in the homebrew launcher y tried to install the menuhax_manager but it fails. i have a screenshot if needed.

I have a question and i don't know if is rigth to ask that here but here i go, it's wise to try a downgrade in order to install a cfw? all the guides recomend to install the 9.2 firmare but i cant find that frimware for the korea new 3ds anywhere.

I'm going to test a little more and update the information if necesary.

**Comment by Patron182** [comment]
It works perfectly. Thank you :)

Once in the homebrew launcher y tried to install the menuhax_manager but it fails. i have a screenshot if needed.

I have a question and i don't know if is rigth to ask that here but here i go, it's wise to try a downgrade in order to install a cfw? all the guides recomend to install the 9.2 firmare but i cant find that frimware for the korea new 3ds anywhere.

I'm going to test a little more and update the information if necesary.

**Comment by Patron182** [comment]
It works perfectly. Thank you :)

Once in the homebrew launcher y tried to install the menuhax_manager but it fails. i have a screenshot if needed.

I have a question and i don't know if is rigth to ask that here but here i go, it's wise to try a downgrade in order to install a cfw? all the guides recomend to install the 9.2 firmare but i cant find that frimware for the korea new 3ds anywhere.

I'm going to test a little more and update the information if necesary.

**Comment by yellows8** [comment]
@Patron182 Er, did you delete duplicate comments at the same time I did? :|

**Comment by yellows8** [comment]
Regarding menuhax_manager see README - downgrading belongs elsewhere(like gbatemp). Downgrading on New3DS KOR (probably) isn't documented anywhere though.

**Comment by Patron182** [comment]
@yellows8 Sorry about the duplicated comments I delete them as soon as I realized.

Thanks for the info i will research and update as soon as i can.

**Comment by d3m3vilurr** [comment]
@Patron182 
1. sadly, you can't use menuhax. Korea console not have theme feature. menuhax trigger use this data at the 3ds boot process
2. also sadly, downgrade is hard and useless.
   - kor n3ds downgrade rom finding is very hard. many 3ds forums just uploaded usa, jpn, eur versions.
   - also sadly, nintendo does not provide old version updates.
   - first uploaded update data is v9.6 (just partially). so you cannot be use if you can get them.(you only can get versions are 9.7 to 10.7 if exists on the internet)
   - many homebrew apps use [svchax](https://github.com/aliaspider/svchax). but currently this code cause stuck on the kor n3ds.

**Comment by yellows8** [comment]
"Korea console not have theme feature." https://github.com/yellows8/3ds_homemenuhax#supported-system-versions "KOR builds are included in the release-archive starting with v2.0. "

**Comment by Patron182** [comment]
@d3m3vilurr @yellows8 thank you very much for all the help you guys gave me, at least i have region free :)
