### ISSUE TITLE
Certain themes break New3DS browserhax.

### ISSUE THREAD

**Issue by yellows8** [yellows8/3ds_browserhax_common#37]
According to a number of people, certain themes(official/custom) cause New3DS browserhax-loader to fail(orange screen).

It seems like Home Menu takeover fails somehow, but I _still_ haven't debugged this yet(didn't have any themes on New3DS which trigger it last time I checked). Leave a comment here if you know of any themes which trigger this(ideally not any paid themes).

**Comment by yellows8** [comment]
Finally got it to trigger myself(checked IRC logs), with two no-BGM custom-themes installed with shuffling(Home Menu crashed).

**Comment by TheGreekBoy** [comment]
@yellows8 this means possible support for 10.6/10.7?

**Comment by yellows8** [comment]
No comment.

**Comment by yellows8** [comment]
Finally fixed in a local commit.
