### ISSUE TITLE
Hello Yellows8

### ISSUE THREAD

**Issue by DD2XAlpha** [yellows8/3ds_browserhax_common#40]
I have something (I think it be interesting) for the 3DS but I dont know if it have potential on HAX. How Can I talk to you?

**Comment by yellows8** [comment]
EFNet IRC privmsg.

**Comment by DD2XAlpha** [comment]
ok, so how can I found you?

**Comment by yellows8** [comment]
Send me an IRC privmsg. https://3dbrew.org/wiki/3dbrew:About

**Comment by DD2XAlpha** [comment]
I cant login in the chat and cant found it

**Comment by yellows8** [comment]
http://www.efnet.org/

**Comment by DD2XAlpha** [comment]
Im on the page but cant find your chat

**Comment by DD2XAlpha** [comment]
I am no the chat now
