### ISSUE TITLE
Supported verisons

### ISSUE THREAD

**Issue by RadiantDerg** [yellows8/3ds_browserhax_common#41]
With the supported verisons listed, does the system revision number matter? cause i've been trying this on 10.5 for the past 2 hours, knowing it worked once before. but it isn't now, and the only thing that has changed was the system revision number.

**Comment by yellows8** [comment]
"the only thing that has changed was the system revision number" ?

**Comment by RadiantDerg** [comment]
"-33"

**Comment by yellows8** [comment]
How exactly did you update to the latest NUP-version without a full sysupdate?

**Comment by RadiantDerg** [comment]
Patching Nver

**Comment by RadiantDerg** [comment]
Via NASA

**Comment by yellows8** [comment]
Was installing the latest NVer the only system-title you installed recently?

**Comment by RadiantDerg** [comment]
Friend system-module. eshop  and mint are still 10.7 files. but the Nver and friend sys module are from 11.0

**Comment by yellows8** [comment]
What's the system-version displayed in System-Settings, and what model(Old3DS/New3DS)?

**Comment by RadiantDerg** [comment]
10.5.0-33U o3ds

**Comment by yellows8** [comment]
Be more specific with "not working".

**Comment by RadiantDerg** [comment]
It's not that it's not working, I was just wondering if the revision actually mattered. It crashes at orange, like you mentioned on the browserhax page. but it was probably possible that the file changes i made in nand might've broke it.

**Comment by yellows8** [comment]
The titles you updated in this case don't affect browserhax - sounds like the random failures already mentioned elsewhere.

**Comment by RadiantDerg** [comment]
Alright, thanks. Just gotta keep tryin' I guess :P

**Comment by tommyb008** [comment]
spent 3 days on this
please help
version (web browser) : 1.7622
version(3ds)NEW 10.6.0.32U
tube hax also failed
i have everything on sdcard
plz help

**Comment by yellows8** [comment]
"version(3ds)NEW 10.6.0.32U" ......... Re-read the actual browserhax site.

**Comment by tommyb008** [comment]
my bad i ment 31 not 32 :( theres no hope for me ;(

**Comment by tommyb008** [comment]
whats the actual site?

**Comment by tommyb008** [comment]
nvm
