### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by DaWolfen615** [yellows8/3ds_browserhax_common#44]
I'm trying to install menuhax on firmware 11.0.0-33U using browserhax access
Browserhax worked very well the night before yet menuhax wasn't able to install
Today, however, I read over some solutions for menuhax but couldn't get into browserhax because the server is down (I tried all browsers on multiple devices, all the same 505 Internal Server Error)
Is this temporary? Or is it just local?

P.S.- On Chrome it just says "this site is unreachable"

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues/132#issuecomment-235899655

**Comment by ghost** [comment]
Has this been cleared yet? I was able to access the website an hour ago, but now it seems to be down again.

**Comment by yellows8** [comment]
Just change your 3DS system's DNS-server config if you're having trouble still.

**Comment by ghost** [comment]
That fixed it. Strangely enough, my computer suddenly started doing it too :P

**Comment by DaWolfen615** [comment]
I switched the DNS to 8.8.8.8, which fixed it
Thx
