### ISSUE TITLE
System freezes on Red Screen; have to restart

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_browserhax_common#45]
When using [the autotool](http://yls8.mtheall.com/3dsbrowserhax_auto.php), the screen flashes Yellow, then Gray, then Orange, then White, displays the return for a second, and then flashes Blue, then Green (I think? It was really fast), and finally (again, I think, there may have been one more color) Red. From here, I have to restart the system, as no inputs do anything.

I'm using a New3DS with firmware 11.0.0-33u.

**Comment by ihaveamac** [comment]
did you forget to extract the [starter kit](https://smealum.github.io/ninjhax2/starter.zip) so you have a boot.3dsx and 3ds folder at the root?

**Comment by ghost** [comment]
Welp, that'd likely be it. The install guide made it sound like I did that afterwards. I'll try that once I find a #0 screwdriver...

**Comment by ghost** [comment]
I added the files, plugged the card back in, but now I'm getting:

Error code: 032-1056
Could not display page

When I try to access the installer website.

EDIT: that's just server issues, actually. My computer isn't connecting either.
EDIT2: Well then. The server thing is another instance of issue #44 I think. I'll bring it up there. Don't close yet; haven't been able to re-attempt the install process.

**Comment by ghost** [comment]
Issue resolved.
