### ISSUE TITLE
red screen struck

### ISSUE THREAD

**Issue by Stiggia** [yellows8/3ds_browserhax_common#51]
I'm trying running browserhax on an O3DS 9.2 firmwhere.
Screen changes some  colors (yellow/gray/yellow/gray/green/blu/) then struck on a red screen.
I followed the instructions and many tutorial always the same result.
I have never seen the slidebar in browser before screen start change color.

**Comment by ihaveamac** [comment]
you need to have a boot.3dsx at the root from the starter kit.

**Comment by Stiggia** [comment]
I had

**Comment by ihaveamac** [comment]
make sure it's not corrupt, and that the SD card works with the 3DS (themes, digital games, etc)?

**Comment by Stiggia** [comment]
Rechecked several times redowload reunzipped 
SD seem to woek DS can write data on it
Script seem to start and fail rather to not start at all.

**Comment by Stiggia** [comment]
I've tried to install hbl via .cia. When i started it i got the same results.
Changing the firmware version may be helpfull? which one is the best?

**Comment by yellows8** [comment]
No, that always means loading the /boot.3dsx failed.

**Comment by Stiggia** [comment]
I think is related to my SD card. I tryed another one and works via cia and via browsehax.
So i copied all the card in the previus one, since is bigger, and it did not work.

**Comment by Stiggia** [comment]
OK reformatting SD and lowering the cylinder size solved.

Thanks
