### ISSUE TITLE
Stuck on red screen. Cant find fix.

### ISSUE THREAD

**Issue by bevelle03** [yellows8/3ds_browserhax_common#52]
Running 11.0.0.33.u old 3ds
Downloaded zipped file HB 3ds v3.1.
Placed 3ds folder and boot.3dsx file on DS.
I follow these steps:
1. Turn Off Wi-Fi 
2.  Open web browser and delete cookies history and initialize save data 
3. Re-open web browser and set up save data 
4. Scan QR code and load webpage 
5. Wait for connectivity error  and turn on Wi-Fi then reload webpage 

 I've tried this countless times and every time I get the red screen

**Comment by yellows8** [comment]
That _always_ means loading /boot.3dsx from SD failed.
