### ISSUE TITLE
patch for 11.1 Old3DS?

### ISSUE THREAD

**Issue by DaWolfen615** [yellows8/3ds_browserhax_common#53]
I read on gbatemp.net that Browserhax had reportedly been patched for v11.1 
I just want to know if this is accurate and if there's a download link for it
![screenshot_2016-09-15-00-42-41](https://cloud.githubusercontent.com/assets/20707112/18539500/74c7722a-7add-11e6-9717-2d48a63ca90c.png)

**Comment by yellows8** [comment]
"patched for v11.1 " obviously

"download link" .............................
