### ISSUE TITLE
Browserhax Down?

### ISSUE THREAD

**Issue by calzonees** [yellows8/3ds_browserhax_common#56]
https://yls8.mtheall.com/3dsbrowserhax.php returns a 403 Forbidden error when opened.

**Comment by yellows8** [comment]
The browserhax portion of the site is finally back.

**Comment by nico403** [comment]
and for the ctr httpwn server ?

**Comment by yellows8** [comment]
Yes.

**Comment by nico403** [comment]
thanks

**Comment by nico403** [comment]
I'm waiting for the soft downgrade I need to stay at 11.0, right ?

**Comment by yellows8** [comment]
Not the place to ask that...

**Comment by seeIn2D** [comment]
still unable to dl ctr httpwn config. am i mistaken that the server is back up?

**Comment by nico403** [comment]
For me it works now the servers are back up so ...
