### ISSUE TITLE
1.7567 broken again

### ISSUE THREAD

**Issue by piratesephiroth** [yellows8/3ds_browserhax_common#7]
yeah, not working on O3DS 9.2... again

**Comment by yellows8** [comment]
If you're having the same issue as #6 there's no need to open a duplicate issue.

**Comment by piratesephiroth** [comment]
nah it doesn't even get to a colored screen.

**Comment by piratesephiroth** [comment]
It simply crashes the browser every time.

**Comment by yellows8** [comment]
That's quite normal with sliderhax, just reinitialize savedata etc.

**Comment by piratesephiroth** [comment]
It just never works. Apparently this issue was fixed a while ago but it's back.
https://gbatemp.net/threads/update-browserhax-working-on-old-3ds-v-9-2-0-20u.398651

It seems it misteriously works for some people, though.
https://gbatemp.net/threads/help-browserhax-dont-work-on-9-2-0-20u.407890/#post-5916345

**Comment by yellows8** [comment]
Nothing in the 3ds_browserhax_common repo matters when it "doesn't even get to a colored screen.", it's sliderhax itself failing.

**Comment by titoftit** [comment]
Hi,
I have same problem on O3ds in 9.4. The browser crash every time without any colored screen. ..
