### ISSUE TITLE
not a issue just a heads up

### ISSUE THREAD

**Issue by Reual4412** [yellows8/3ds_browserhax_common#8]
if you are unaware the 3ds did a update to 10.4.0.-29. (I'm just saying chances are you are already aware, if not well heads up)

**Comment by yellows8** [comment]
...........................

**Comment by ghost** [comment]
I hear yellows8 is actually a cat and everything he types into his computer -- just by chance -- happens to be useful code.

**Comment by meowy** [comment]
That's possible!

Source: I'm a cat and everything I type into my computer - just by chance - happens to be useful code.
